# Generated by Django 4.0 on 2022-03-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_education_edu_name_education_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.CharField(max_length=100, verbose_name='text'),
        ),
    ]
