# Generated by Django 4.0 on 2022-03-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_project_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='education',
            new_name='education_place',
        ),
    ]
